name: Test Automation Workflow

on:
  schedule:
  -cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLamdaTest=true -DisHeadless=false
   
    - name: Upload Test Logs
       if:always()
       uses:actions/upload-artifact@v4.6.2
       with:
        name: Test Log
        path: logs/

      - name: Upload screenshots An Artifacts
        if: always()
        users: actions/upload-artifacts@4.4.3
        with:
        name: html-report
        path: report.html
        
      - name: Upload Test Reports
     if: always()
     uses: actions/upload-artifact@v4.6.2
     with:
        name: Test Reports
        path: report.html
    - name: Test Execution Status
    run: echo "Test Execution Completed"

-name: Copy report gh-pages Folder
  if: always()

  run: |
  mkdir-p public/extents-reports
  cp -R report.html public/extent-reports
  cp -R screenshots/public/extent-reports/screesnhots/
  ls -l
-name: Deploy
if: always
users: JamesIves/github-pages-deploy-action@v4
with:
  folder: public/extents-reports/
  token: ${{screets.PAT1234}}
  clean: true
  
  





    















   
